export const ADD_HOLDING = 'ADD_HOLDING';
export const REMOVE_HOLDING = 'REMOVE_HOLDING';
export const UPDATE_HOLDING = 'UPDATE_HOLDING';

export const ERROR_HOLDING = 'ERROR_HOLDING';
export const ERROR_HOLDING_CLEAR = 'ERROR_HOLDING_CLEAR';
export const ADD_HOLDING_START = 'ADD_HOLDING_START';

export const START_REFRESHING = 'START_REFRESHING';
export const STOP_REFRESHING = 'STOP_REFRESHING';

export const ON_INITIAL_LOAD = 'ON_INITIAL_LOAD';

